import type { Metadata } from "next";
import { Geologica,  } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import SessionWrapper from "@/components/SessionWrapper";

const geologica = Geologica({subsets:['latin'],weight:'400'});

export const metadata: Metadata = {
  title: "FINDER",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={geologica.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
